apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  namespace: url-shortener-namespace
  labels:
    app: url-shortener-app
spec:
  selector:
    app: url-shortener-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-deployment
  namespace: url-shortener-namespace
  labels:
    app: url-shortener-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-app
  template:
    metadata:
      labels:
        app: url-shortener-app
    spec:
      containers:
      - name: nginx
        image: 282592278669.dkr.ecr.us-east-1.amazonaws.com/eks-image-repository
        ports:
        - containerPort: 80